id = "try-n3-04-06"
level = "N3"

[question]
text = "A：うー、寒い！風邪ひきそう。コートを（　）。\nB：だから、「コートは？」って聞いたのに。"
choices = ["着てくればよかった", "着てきてよかった", "着てこないでよかった", "着てこなければよかった"]
correct = "着てくればよかった"

[grammar]
main = "てくればよかった"
related = ["てきてよかった", "てこなければよかった"]

tags = [
  "level/N3",
  "grammar/てくればよかった",
  "function/後悔",
  "pattern/複合動詞",
  "pattern/て形"
]
