id = "chokuzen-n3-06-12"
level = "N3"

[question]
text = "旅行会社に聞いて（　）ところ、安い切符が買えた。"
choices = ["みる", "みた", "みない", "みなかった"]
correct = "みた"

[grammar]
main = "Vたところ（试着做了……结果发现……）"
related = [
  "Vるところ（正要……的时候）",
  "Vているところ（正在……的时候）",
  "Vたところ（刚…… / 做了之后结果……）",
  "Vてみる（试着做某事）"
]
tags = [
  "level/N3",
  "grammar/たところ",
  "function/尝试・结果",
  "pattern/書き言葉・口語表現両方"
]

[examples]
1 = "先生に今度（こんど）のテストの範囲（はんい）を聞（き）いたところ、10課（か）までだと言（い）われた。\n我问了老师这次考试的范围，结果被告知是到第10课。"
2 = "歯（は）が痛（いた）いので歯医者（はいしゃ）さんに行（い）ったところ、ひどい虫歯（むしば）になっていると言（い）われた。\n因为牙疼所以去了牙医，结果被告知已经是严重的蛀牙。"
3 = "旅行会社（りょこうがいしゃ）に聞（き）いてみたところ、安（やす）い切符（きっぷ）が買（か）えた。\n去旅行社问了一下，结果买到了便宜的票。"
