id = "chokuzen-n2-03-13"
level = "N2"

[question]
text = "あんなにいい人が悪いことをするなんて、あり（　）。"
choices = ["える", "うる", "えない", "うない"]
correct = "えない"

[grammar]
main = """
〜ありえる／ありうる／ありえない（可能性表达）
【意味】
表示“有可能／不可能”。用于说明事情是否有可能发生。
「ありえる」「ありうる」都表示“可能性存在”，
「ありえない」表示“绝不可能”。
【接続】動詞「ある」＋得る（える）
【例文】
・そんなことも**ありえる**。（那种事也可能发生）
・事故はいつでも**ありうる**。（事故随时可能发生）
・彼がそんなことをするなんて**ありえない**！（他不可能那样做）
"""
related = ["〜得る（うる／える）"]
tags = [
  "level/N2",
  "grammar/ありえる",
  "grammar/ありえない",
  "function/可能性",
  "pattern/口語表現"
]
