id = "chokuzen-n2-02-04"
level = "N2"

[question]
text = "悩み（　）、結局、彼は真実を話した。"
choices = ["かけて", "ぬいて", "えて", "かぎって"]
correct = "ぬいて"

[grammar]
main = """
〜抜く（ぬく）（坚持到底／彻底做完）
【意味】表示经过长时间努力、痛苦或挣扎，坚持到底完成某事。带有“经历到最后”的语气。
【接続】動詞ます形＋ぬく
【例文】
・悩み**ぬいて**、答えを出した。
・最後まで戦い**ぬく**。
・困難を乗り越え**ぬいた**人生。

【比較】
・〜かける：动作进行中，未完成（例：読みかける）
・〜得る：表示可能性（例：起こり得る）
・〜に限って：名詞＋に限って（偏偏〜／唯独〜）
"""
related = ["〜きる", "〜とおす"]
tags = [
  "level/N2",
  "grammar/〜ぬく",
  "function/程度・継続",
  "pattern/書き言葉"
]
