id = "chokuzen-n2-01-10"
level = "N2"

[question]
text = "修理すれば（　）けれど、古いから捨てよう。"
choices = ["使えないものだ", "使ってはならない", "使わねばならない", "使えないこともない"]
correct = "使えないこともない"

[grammar]
main = """
〜ないこともない（也不是不能……／勉强可以）
【意味】表示弱肯定、委婉承认。
【接続】動詞ナイ形＋こともない／い形容詞ナイ形＋こともない
【例文】
・修理すれば使えないこともない。
・お金がないこともないけど、今は使いたくない。

〜てはならない（禁止／不允许做）
【意味】禁止做某事，相当于“must not”或“cannot”。
【接続】動詞て形＋はならない
【例文】
・ここでタバコを吸ってはならない。
・この資料にサインする前に、よく読んで**てはならない**。
"""
related = ["〜わけではない", "〜というわけでもない", "〜ないでもない"]
tags = [
  "level/N2",
  "grammar/〜ないこともない",
  "function/婉曲肯定",
  "pattern/複否定"
]
