id = "chokuzen-n2-02-07"
level = "N2"

[question]
text = "まだ古いのが残っているから、使い（　）から新しいのを使おう。"
choices = ["かけて", "えて", "きって", "ぬいて"]
correct = "きって"

[grammar]
main = """
〜きる（彻底做完／完全……）
【意味】表示动作做到极致，完全结束。用于强调“用尽、完结”的意思。
【接続】動詞ます形＋きる
【例文】
・ご飯を全部食べ**きった**。（饭吃光了）
・力を出し**きった**。（全力以赴）
・使い**きって**から新しいのを使おう。（用完旧的再用新的）
"""
[grammar_addon]
point = "から 的两种主要用法"
details = """
1️⃣ 【原因】“因为……”
　例：雨が降っている**から**、出かけません。
　→ 因为下雨所以不出门。

2️⃣ 【时间顺序】“在……之后”
　例：ご飯を食べて**から**寝る。
　→ 吃完饭再睡。

📘 本题用的是【时间顺序】用法：
　使いきって**から**新しいのを使おう。
　→ 把旧的用完以后再用新的。
"""

related = ["〜かける", "〜ぬく", "〜とおす"]
tags = [
  "level/N2",
  "grammar/〜きる",
  "function/程度・完了",
  "pattern/書き言葉"
]
