id = "chokuzen-n2-01-13"
level = "N2"

[question]
text = "映画館には10年以上行っていない。（　）こともないが、家でビデオを見るほうが楽だ。"
choices = ["行くことはない", "行きたい", "行きたくない", "行った"]
correct = "行きたくない"

[grammar]
main = """
〜ことはない（不需要做某事）
【意味】表示“不做某事是完全可以的，**不需要**做某事”，强调不做某事是**完全可以的**。
【接続】動詞の普通形 + ことはない
【例文】
・こんなことで心配することはない。
・映画館に行くことはないが、家で映画を見るほうが楽だ。

〜ないことはない（并非完全不行）
【意味】表示“**并非完全不行**，但有条件做某事”，表示一种**勉强可以接受**的态度，带有保留语气。
【接続】動詞の普通形 + ないことはない
【例文】
・映画館に行かないことはないが、家で映画を見るほうが楽だ。
・これをやらないことはないが、時間がかかりすぎる。
"""
related = ["〜ことはない", "〜ないこともない", "〜わけではない"]
tags = [
  "level/N2",
  "grammar/〜ことはない",
  "function/否定・強調",
  "pattern/口語表現"
]
