id = "chokuzen-n2-02-06"
level = "N2"

[question]
text = "勉強していないところ（　）、試験に出る。"
choices = ["にとって", "にしたら", "にかぎって", "にともなって"]
correct = "にかぎって"

[grammar]
main = """
〜にかぎって（偏偏／唯独）only
【意味】
① 表示限定，意为“只限于……”“唯独……”。
② 表示与平常不同的特例，常带有抱怨或惊讶语气。
③ 表示说话人对某人／某事的信赖（“唯独他不会……”）。
【接続】名詞＋にかぎって
【例文】
・今日**にかぎって**雨が降る。
・勉強していないところ**にかぎって**試験に出る。
・彼**にかぎって**そんなことをするはずがない。
"""
related = ["〜に限り", "〜に限っては", "〜に限らず"]
tags = [
  "level/N2",
  "grammar/〜にかぎって",
  "function/限定・特例",
  "pattern/口語表現"
]
