id = "chokuzen-n2-02-05"
level = "N2"

[question]
text = "生徒がやる気を出さない（　）、いくら先生が一生懸命教えても上達しないでしょう。"
choices = ["かぎり", "ほど", "くらい", "とともに"]
correct = "かぎり"

[grammar]
main = """
〜かぎり（限り）（只要……就……） as long as
【意味】表示“只要……就……”。用于说明在某条件不改变的范围内，后项的状态也不会改变。
【接続】
・動詞普通形＋かぎり
・い形容詞＋かぎり
・な形容詞＋なかぎり
・名詞＋であるかぎり
【例文】
・努力し**ないかぎり**、成功しない。
・学生である**かぎり**、勉強は続けなければならない。
・生徒がやる気を出さない**かぎり**、上達しない。
"""
related = ["〜限りでは", "〜ない限り", "〜限りに"]
tags = [
  "level/N2",
  "grammar/〜かぎり",
  "function/条件・範囲",
  "pattern/書き言葉"
]
