id = "chokuzen-n2-04-03"
level = "N2"

[question]
text = "新しい情報が（　）次第、お知らせします。"
choices = ["入り", "入る", "入って", "入った"]
correct = "入り"

[grammar]
main = "Vます連用形＋次第：一旦前项完成，立刻进行后项（正式書き言葉）。例：準備ができ次第、出発します。『入る→入り次第』"
related = [
  "Vた＋次第です：刚刚……，特此说明/报告（句末固定用法，不能接主句）。例：先ほど戻った次第です。",
  "Vたら：……的话就……（口语，时间条件）"
]
tags = [
  "level/N2",
  "grammar/次第",
  "function/順接・即時",
  "pattern/書き言葉・連用形接続"
]
