id = "try-n2-08-04"
level = "N2"
mistakes = 2

[question]
text = "びんのふたを開けるのにいつも苦労していた。（　）この商品を開発したわけです。"
choices = ["すると", "さて", "そこで", "なお"]
correct = "そこで"

[grammar]
main = "‘そこで’ 表示因果关系，常用于前述问题或情况后，解释发生的结果或采取的行动。"
related = ["接续助词", "因果関係"]
tags = [ "level/N2", "grammar/接续助词", "function/因果", "pattern/口語表現" ]

[options]
1 = "すると: 通常用于‘(结果)……’"
2 = "さて: 用于话题的转移，常用于引入新的话题，不能用于表达因果关系。"
3 = "そこで: 表示因果关系，相当于‘因此、在这种情况下’，适合用来连接困难和结果。"
4 = "なお: 用于补充说明或进一步解释，常用于附加信息，不适用于因果关系。"

