id = "try-n2-07-07"
level = "N2"
mistakes = 2

[question]
text = "当学会は、研究者や専門家（　）、企業や個人の方々にも広く開かれた学会です。"
choices = ["に反して", "に比べて", "のみならず", "にもかかわらず"]
correct = "のみならず"

[grammar]
main = "のみならず（＝のみ＋ならず：「のみ」＝だけ、「ならず」＝〜だけでなく）"
related = ["だけでなく", "ばかりか", "にもかかわらず"]
tags = [
    "level/N2",
    "grammar/のみならず",
    "function/添加・強調",
    "pattern/書き言葉"
]

[usage]
# 「〜のみならず」表示“不仅……而且……”，语气正式，多用于书面语。
# 构成：のみ（＝だけ）＋ならず（＝〜だけでなく）
# 表示前项不仅成立，后项也同样成立，常见于说明文、公告、学术文章。
# 对比：
# - 「だけでなく」：口语、自然。
# - 「ばかりか」：语气更强，有“连……也……”的惊讶意味。
# - 「にもかかわらず」：逆接，用于“尽管……仍然……”，与本题无关。
