id = "try-n2-11-06"
level = "N2"

[question]
text = "外国語を勉強するならその国に留学する（　）と私は思う。"
choices = ["に限る", "にほかならない", "にすぎない", "ばかりだ"]
correct = "に限る"

[grammar]
main = "〜に限る（……是最好的／莫过于……）"
related = ["〜にほかならない（无非是／正是/不是别的(ほか(他))）", "〜にすぎない（只不过是……而已）"]
tags = [
  "level/N2",
  "grammar/に限る",
  "function/判断・最適",
  "pattern/口語表現"
]

[structure]
parts = [
  "に：格助詞，标示对象/基准",
  "限る：動詞，‘限定’之意，引申为‘最适合’",
  "〜に限る：表达主观推荐，常与「〜と思う／〜のが一番だ」呼应"
]

[notes]
why_not_2 = "「にほかならない」多接名词或『〜ということ』：N/（Vすること）+ にほかならない。句子若写成『留学するにほかならない』不自然，而且该表达是强断定语气，不合『〜と私は思う』的主观推荐语境。"
example_good = "外国語を学ぶなら現地に住むに限る。"
example_hokan = "彼が成功したのは努力の結果にほかならない。"
