id = "try-n2-11-04"
level = "N2"

[question]
text = "被災地でボランティアをした（　）、たった１日だけですから…。"
choices = ["ばかりでなく", "というのに", "というより", "といっても"]
correct = "といっても"

[grammar]
main = "〜といっても（虽说……但……）"
related = ["〜というのに（明明……却……）", "〜というより（与其说……不如说……）"]
tags = [
  "level/N2",
  "grammar/といっても",
  "function/逆接・程度修正",
  "pattern/口語表現"
]

[structure]
parts = [
  "と：引用助词，表示前项内容是一个事实或说法。",
  "いっても：動詞『言う』的て形＋も，表示『虽说那样……但……』的语气。",
  "〜といっても：用于对前项的事实进行轻微否定或程度上的弱化。"
]
meaning = "表示虽说前项是事实，但后项指出实际情况与之不同或程度有限。"
mnemonic = "看到『虽说……但其实……』或『たった〜だけ』这种谦虚语气时，常用『〜といっても』。"
example = "留学したといっても、３ヶ月だけです。→ 虽说留过学，但也就三个月而已。"
