id = "try-n2-03-08"
level = "N2"
mistakes = 2

[question]
text = "A：部長、パソコンの本、ずいぶん熱心に読んでますね。\nB：うん。パソコンが使えなかったら何もできないんだから、できないと（　）からね。"
choices = ["言うというものではない", "言いかねない", "言わざるを得ない", "言ってはいられない"]
correct = "言ってはいられない"

[grammar]
main = "てはいられない"
related = ["というものではない", "言いかねない", "言わざるを得ない"]
tags = [
  "level/N2",
  "grammar/てはいられない",
  "function/行动必要・紧迫",
  "pattern/動詞て形＋はいられない"
]
