id = "try-n2-02-01"
level = "N2"
mistakes = 2

[question]
text = "水泳は子どもからお年寄りまで世代（　）楽しめるスポーツだと言われている。"
choices = ["ばかりでなく", "に限って", "を問わず", "とおりに"]
correct = "を問わず"

[grammar]
main = "を問わず"
related = ["にかかわらず", "に関係なく"]
tags = ["level/N2", "grammar/を問わず", "function/範囲/制限なし", "pattern/書き言葉"]
