id = "try-n2-09-07"
level = "N2"

[question]
text = "A：強化合宿、どうだった？ B：まいったよ。ほんと、死んだ（　）と思うくらいつかれたよ。"
choices = ["ほうがましだ", "ところだった", "ことだ", "おそれがある"]
correct = "ほうがましだ"

[grammar]
main = "〜ほうがましだ（还不如……算了／……比较好）"
related = ["〜くらいなら（与其……还不如……）", "〜より（比……）"]
tags = [
  "level/N2",
  "grammar/ほうがましだ",
  "function/比較・評価",
  "pattern/口語表現"
]

[structure]
parts = [
  "ほう：名词，意为『方向、方面、选择』",
  "が：助词，表示主语或对比",
  "まし（増し）：名词／形容動詞词干，意为『稍好一点、算不错』",
  "だ：断定助动词，表示判断"
]
meaning = "用于表达在两个消极选项中，后者稍好一点的主观判断。口语中常带有抱怨或夸张语气，如『死んだほうがましだ』＝‘还不如死了算了’。"
mnemonic = "『ほう（方向）＋がまし（稍好）＋だ』→ 表示“选那边还稍好点”。"
example = "あんなにつらい仕事をするくらいなら、辞めたほうがましだ。→ 与其做那种苦差事，还不如辞职。"
