id = "try-n2-06-01"
level = "N2"

[question]
text = "卒業論文が間に合わなかった（　）、卒業が半年遅れてしまった。"
choices = ["ばかりに", "からには", "ものの", "にもかかわらず"]
correct = "ばかりに"

[grammar]
main = "ばかり（＝仅仅・偏偏）＋に（＝原因・理由）"
related = ["からには", "ものの", "にもかかわらず"]
tags = [
    "level/N2",
    "grammar/ばかりに",
    "function/原因・結果・後悔",
    "pattern/書き言葉"
]

[usage]
# 🔹 语法说明
# 「ばかりに」由「ばかり（仅仅・偏偏）」＋「に（原因・理由）」组成。
# 含义：正因为某个小原因，结果导致了不好的结果（常带后悔语气）。
#
# 例：
# - 信じたばかりに、だまされた。 → 就因为相信了他，结果被骗了。
# - 一言多く言ったばかりに、彼を怒らせてしまった。 → 就因为多说了一句，把他惹生气了。
#
# 🔹 助词「に」的语感：
# 「に」的核心含义是“方向・结果的指向”，
# 当用于感情或状态变化时，引申为“由……引起、因为……导致”。
# 因此「ばかりに」整体表示“由于仅仅……这个原因”。
#
# 🔹 对比：
# - 「からには」：既然……就……（表示理所当然、义务或决心）
# - 「ばかりに」：因为……导致坏结果（带后悔语气）
