id = "try-n2-06-04"
level = "N2"

[question]
text = "まだ時間はありますから、急ぐ（　）よ。"
choices = ["どころではありません", "わけにはいきません", "おそれがあります", "ことはありません"]
correct = "ことはありません"

[grammar]
main = "ことはない（＝する必要はない）"
related = ["わけにはいかない", "どころではない", "おそれがある"]
tags = [
    "level/N2",
    "grammar/ことはない",
    "function/不要・必要否定",
    "pattern/口語"
]

[usage]
# 「〜ことはない」表示“没有必要做某事”，语气温和，多用于安慰或劝说。
# 例：
# - 心配することはありません。（不用担心。）
# - 急ぐことはないよ。（不用急。）
#
# 对比：
# - 「わけにはいかない」：因为义务或道德原因“不能做”。
#   例：嘘をつくわけにはいかない。（不能撒谎。）
# - 「どころではない」：根本不是做某事的时候。
#   例：今は勉強どころではない。（现在根本没法学习。）
# - 「おそれがある」：有……的可能（负面）。
#   例：大雨で川があふれるおそれがある。（有因大雨河水泛滥的可能。）
