id = "try-n2-11-02"
level = "N2"
mistakes = 2

[question]
text = "食べ物を売る店は、どんな店（　）衛生管理をきちんとしなければならない。"
choices = ["にしては", "にしろ", "につけ", "ばかりか"]
correct = "にしろ"

[grammar]
main = "〜にしろ／〜にせよ（即使……也……／无论……都……）"
related = ["〜としても（即使……也……）", "〜たとえ〜ても（即使……也……）", "〜にしても（无论……也……）"]
tags = [
  "level/N2",
  "grammar/にしろ",
  "function/逆接・列挙",
  "pattern/書き言葉"
]

[structure]
parts = [
  "に：格助词，表示条件或对象。",
  "しろ：動詞『する』的命令形，用于形成让步或假定语气。",
  "〜にしろ：可表达『即使……也……』的让步，或『无论……还是……』的列举，两种语气都强调后项成立。"
]

[usage]
type1 = "① 让步用法：即使……也……"
example1 = "どんなに忙しいにしろ、連絡ぐらいはするべきだ。→ 不管多忙，也该打个电话。"
note1 = "相当于『たとえ〜ても』，表示假设情况也不改变结果。"

type2 = "② 列举用法：无论……还是……"
example2 = "学生にしろ社会人にしろ、時間を守ることは大切だ。→ 无论是学生还是上班族，守时都很重要。"
note2 = "相当于『〜にしても〜にしても』，强调多种情况都同样适用。"

meaning = "表示即使在某种情况下、或无论哪种情况，后项的判断依然成立。语气正式，多用于书面语。"
mnemonic = "看到『どんな〜でも』『無論〜でも』语义时，常可用『〜にしろ／〜にせよ』，既能表达让步也能表达列举。"
example = "どんな理由にしろ、人を傷つけてはいけない。→ 无论什么理由，都不能伤害别人。"
