id = "try-n2-12-03"
level = "N2"

[question]
text = "工場建設（　）、部長は打ち合わせのためにロシアへ向かった。"
choices = ["において", "に先立って", "にわたって", "につけ"]
correct = "に先立って"

[grammar]
main = "〜に先立って（在……之前）"
related = ["〜前に（在……之前）", "〜に際して（在……之际）"]
tags = [
  "level/N2",
  "grammar/に先立って",
  "function/時間・順序",
  "pattern/書き言葉"
]

[structure]
parts = [
  "に：格助詞，表示时间基准。",
  "先立つ（さきだつ）：动词，意为『走在前面／领先／先于』。",
  "〜に先立って：相当于『〜の前に』，但语气更正式，常用于重大活动、计划、会议等场合。"
]
meaning = "表示在某重要行动或事件发生之前先进行某事。语气比『〜前に』更正式。"
mnemonic = "看到『打ち合わせ』『準備』『開会』『出発』等事前行为时，常用『〜に先立って』。"
example = "開会に先立って、代表が挨拶をします。→ 开幕之前，代表将致辞。"
